"""Add last_status_change column to applications

Revision ID: 48a64ea6cb7c
Revises: 5877edff2f1b
Create Date: 2025-08-07 18:54:21.611279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a64ea6cb7c'
down_revision = '5877edff2f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_status_change', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('last_status_change')

    # ### end Alembic commands ###
