"""Add author_id to application_logs table

Revision ID: 5877edff2f1b
Revises: 
Create Date: 2025-08-07 18:34:24.444960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5877edff2f1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_application_logs_author_id', 'users', ['author_id'], ['id'])

    with op.batch_alter_table('application_types', schema=None) as batch_op:
        batch_op.alter_column('execution_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_types', schema=None) as batch_op:
        batch_op.alter_column('execution_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))

    with op.batch_alter_table('application_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_application_logs_author_id', type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
